export const SLIDER_DEFAULT_SLIDE = 'default'
export const SLIDER_DEFAULT_WITHOUT_GRAYSCALE_SLIDE = 'default_without_grayscale'
export const SLIDER_SLIDE_LINK = 'link'
export const SLIDER_SLIDE_SOLO = 'SLIDER_SLIDE_SOLO'
export const SLIDER_SLIDE_WITH_TEXT = 'text'
export const SLIDER_GRID_3_2 = 'grid_3:2'
export const SLIDER_GRID_1_2 = 'grid_1:2'